# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

############################
# Builder Stage
############################
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package files and source
COPY browserbase/package.json browserbase/package-lock.json ./
COPY browserbase/tsconfig.json ./
COPY browserbase/src ./src

# Install dependencies and build
RUN npm install && npm run build

############################
# Runner Stage
############################
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy built artifacts and needed package metadata
COPY --from=builder /app/dist ./dist
COPY browserbase/package.json browserbase/package-lock.json ./

# Install only production dependencies without running build scripts
RUN npm install --production --ignore-scripts

# Default command to start the MCP server
ENTRYPOINT ["node", "dist/index.js"]
